In [1]:
import numpy as np

In [2]:
transition_mat = np.array([[0.5, 0.8], [0.5, 0.2]])
transition_mat

array([[0.5, 0.8],
       [0.5, 0.2]])

In [3]:
emission_mat = np.array([[0.3, 0.5], [0.6, 0],[0.1, 0.5]])
emission_mat

array([[0.3, 0.5],
       [0.6, 0. ],
       [0.1, 0.5]])

In [4]:
initial_state_prob = np.array([[1, 0]])
initial_state_prob

array([[1, 0]])

In [5]:
v = np.array([0,1,0,2,0,2,1,0,2,0])
v

array([0, 1, 0, 2, 0, 2, 1, 0, 2, 0])

In [6]:
alpha = np.zeros((10,2))
for i in range(10):
    if i == 0:
        alpha[i,:] = emission_mat[v[i],:] * initial_state_prob 
    else:
        alpha[i,:] = emission_mat[v[i],:] * (transition_mat @ alpha[i-1,:]) 

In [7]:
alpha

array([[3.00000000e-01, 0.00000000e+00],
       [9.00000000e-02, 0.00000000e+00],
       [1.35000000e-02, 2.25000000e-02],
       [2.47500000e-03, 5.62500000e-03],
       [1.72125000e-03, 1.18125000e-03],
       [1.80562500e-04, 5.48437500e-04],
       [3.17418750e-04, 0.00000000e+00],
       [4.76128125e-05, 7.93546875e-05],
       [8.72901563e-06, 1.98386719e-05],
       [6.07063359e-06, 4.16612109e-06]])

In [76]:
alpha_10 = alpha[9,:]
end_alpha = alpha_10/np.linalg.norm(alpha_10)
end_alpha, np.linalg.norm(alpha_10)

(array([0.82451335, 0.5658425 ]), 7.362686819181889e-06)

In [10]:
def forward(V, A, T, I):
    alpha = np.zeros((V.shape[0], T.shape[0]))
    for i in range(V.shape[0]):
        if i == 0:
            alpha[i,:] = A[V[i],:] * I
        else:     
            alpha[i,:] = A[V[i],:] * (T @ alpha[i-1,:])
    return alpha

In [12]:
alpha = forward(v, emission_mat, transition_mat, initial_state_prob)

In [14]:
alpha

array([[3.00000000e-01, 0.00000000e+00],
       [9.00000000e-02, 0.00000000e+00],
       [1.35000000e-02, 2.25000000e-02],
       [2.47500000e-03, 5.62500000e-03],
       [1.72125000e-03, 1.18125000e-03],
       [1.80562500e-04, 5.48437500e-04],
       [3.17418750e-04, 0.00000000e+00],
       [4.76128125e-05, 7.93546875e-05],
       [8.72901563e-06, 1.98386719e-05],
       [6.07063359e-06, 4.16612109e-06]])

In [83]:
def backward(V,A,T):
    beta = np.zeros((V.shape[0], T.shape[0]))
    for i in range(V.shape[0]):
        if i == 0:
            beta[i,:] = [1,1]
        else:
            beta[i,:] = np.transpose(T) @ (A[v[10-i],:]*beta[i-1,:])
    return beta

In [84]:
beta = backward(v, emission_mat, transition_mat)
beta 

array([[1.00000000e+00, 1.00000000e+00],
       [4.00000000e-01, 3.40000000e-01],
       [1.05000000e-01, 6.60000000e-02],
       [3.22500000e-02, 3.18000000e-02],
       [9.67500000e-03, 1.54800000e-02],
       [4.35375000e-03, 2.32200000e-03],
       [1.23356250e-03, 1.27710000e-03],
       [3.80953125e-04, 2.26395000e-04],
       [1.13741719e-04, 1.14068250e-04],
       [3.41225156e-05, 5.45960250e-05]])