# Assignment 3

## Question 1
### part a)

In [5]:
import numpy as np

In [6]:
H = np.array([[1,1,1,1,0,0],[0,0,1,1,0,1], [1,0,0,1,1,0]])

In [65]:
def system_encoding(H):
    n_rows, n_columns = H.shape
    H_hat = np.zeros((H.shape))
    
    for i in range(n_columns):
        H_hat[:,i] = H[:, i]
     
    
    for j in range(n_rows):
        found = False
        dummy = np.zeros((H.shape))
        for i in range(n_columns):
            if (np.sum(H_hat[:,i]) == 1) & (H_hat[j,i] == 1) & (found==False):
                dummy[:,n_columns-n_rows+j] = H_hat[:,i].T
                dummy[:,i] = H_hat[:, n_columns-n_rows+j]
                found = True
                    
            elif np.sum(dummy[:,i]) == 0:
                dummy[:,i] = H_hat[:,i]
        
        H_hat = dummy
    
            
    G = np.zeros((n_columns, n_columns-n_rows))
    G[:n_columns - n_rows, :n_columns - n_rows] = np.eye(N=n_columns-n_rows)
    G[n_columns - n_rows:, :n_columns - n_rows] = H_hat[:, :n_columns-n_rows]
    return H_hat, G

In [8]:
A = np.array([[1,0,1,0,0,1], [0,1,1,0,0,1], [0,0,0,0,1,1]])

In [9]:
B = np.array([[1,1,0,1,0,0], [0,0,1,1,0,0], [1,0,0,1,1,0], [0,0,0,0,0,1]])

In [10]:
C = np.array([[1,1,0,0,1,0],[1,1,0,0,0,1],[1,0,0,1,0,0]])

In [66]:
print(H)
print('\n')
H_bar,G_bar = system_encoding(H)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 1 1 0 0]
 [0 0 1 1 0 1]
 [1 0 0 1 1 0]]


[[1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]


In [67]:
print(np.sum(H_bar@G_bar@np.array([0,0,0]).T)%2)

0.0


In [68]:
print(A)
print('\n')
H_bar,G_bar = system_encoding(A)
print(H_bar)
print('\n')
print(G_bar)

[[1 0 1 0 0 1]
 [0 1 1 0 0 1]
 [0 0 0 0 1 1]]


[[0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 0.]]


In [69]:
print(B)
print('\n')
H_bar,G_bar = system_encoding(B)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 1 0 0]
 [0 0 1 1 0 0]
 [1 0 0 1 1 0]
 [0 0 0 0 0 1]]


[[1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


[[1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]]


In [70]:
print(C)
print('\n')
H_bar,G_bar = system_encoding(C)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 0 1 0]
 [1 1 0 0 0 1]
 [1 0 0 1 0 0]]


[[1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]]


In [78]:
D = np.array([[1,1,0,1,0,0],[0,0,1,1,0,1], [0,0,0,1,1,0]])
print(D)
print('\n')
H_bar,G_bar = system_encoding(D)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 1 0 0]
 [0 0 1 1 0 1]
 [0 0 0 1 1 0]]


[[1. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 0. 0.]]


### part c)

In [126]:
with open('H1.txt', 'r') as f:
    H1 = [[int(num) for num in line.split(' ')] for line in f]
H1 = np.array(H1)

with open('y1.txt', 'r') as f:
    y1 = [[int(num) for num in line.split(' ')] for line in f]
y1 = np.array(y1)   
H1_hat, G1 = system_encoding(H1)

In [127]:
print(H1.shape)
#print(G1.shape)
#print(np.sum(H1_hat))
#print(np.sum(H1_hat,axis=0)%2)

(750, 1000)
3000.0


In [ ]:
def genBinary(n, i, pos_i):
    #generates binary sequences of length n for an i in pos_i position
    sequences = np.zeros((2**(n-1), n))
    sequences[:, pos_i] = i*np.ones((2**(n-1),1))
    
                 
    
    for n in range(n):
        for j in range(2):
            pass
            

In [125]:
def ldpc_decoder(H_hat, y, p, max_iter = 20):
    # This function should be used to do loopy belief propogation on our recieved signal y and return a vector
    # which reperesents the decoded output message.
    # This function should work on the assumption we using the Binary symetric channel
    # It should also output a zero if the a solution was reached and algorithm converged and -1 if it is not.
    
    # Going to need to set up priors and messages which are going to be sent around the system 
    
    n_rows, n_cols = H_hat.shape
    
    # n_rows is the number of partity checks we have and therefore factors in our graph 
    # So we need to go over the iterations and do a pass throuhg the whole system
    # n_cols is the number of features we have 
    
    # 1) Initialise (outside for loop) - p(yn|xn)
    # 2) Factor to variable messages
    # 3) Variable to factor messages
    # 4) Calculate marginals - go back through the steps after this
    
    initials = np.zeros((2, n_cols))
    
    #Here compute the initail probs P(yn|xn) for each value of xn and given yn values (these are first var to factor messages)
    for n in range(n_cols):
        for i in range(2):
            initials[i,n] = p**(i-y[n,0])*(1-p)**(i-y[n,0]+1)
    
    #Define a dictionary has each variable and the checks associatied with it
    variables_and_checks = {}
    checks_and_variables = {}
    #cylce over variables
    for n in range(n_cols):
        #cycle of checks
        for m in range(n_rows):
            if H_hat[m,n] == 1 and (n not in variables_and_checks):
                variables_and_checks[n] = [m]
            elif H_hat[m,n] == 1:
                variables_and_checks[n].append(m)
                
            if H_hat[m,n] == 1 and (m not in checks_and_variables):
                checks_and_variables[m] = [n]
            elif H_hat[m,n] == 1:
                checks_and_variables[m].append(n)
                
    #print(variables_and_checks)
    #print(checks_and_variables)
    
    #Marginals - initialise the marginals that will beproduced at each each iteration
    marginals = np.zeros((2,n_cols))
    
    #Intitalise the factor to variable messages
    messages_fv = np.zeros((2,n_cols))
    
    #Initialise the variable to factor messages
    messages_vf = np.zeros((2, n_rows))
    
    # Now we go through each iteration and doing all message passing
    for iTer in range(max_iter):
        
        # We compute factor to variable messages based off the parity check matrix
        for n in range(n_cols):
            mess = np.ones((2, len(variables_and_checks[n])))
            # Now lets loop through the checks we need to do
            for check in variables_and_checks[n]:
                # loop through the possible values of our variable and generate hte messages assoicated with it.
                for i in range(2):
                    # The number of varlues in theis parity check are as follows
                    num_parity_bits = len(checks_and_variables[check])
                    
                    tries = genBinary(num_parity_bits, i, checks_and_variables[check].index(n))
                    
                    for row in range(tries.shape[0]):
                        if np.sum(tries[row])%2 == 0:
                            for num in tries[row]: checks_and_variables[check]:
                                if checks_and_variables[check][num]!= n:
                                    # Times by the associated messages.
                                    mess[i, check]*= initials[num,checks_and_variables[check][num]]
                                    
                
                    
                    
                    
                    
                
                
#             for i in range(2):
#                 #now get each parity check associated with the variable 
#                 for check in variables_and_checks[n]:
#                     #create the possible values to fill in
#                     values = np.concatenate(np.zeros((1,len(checks_and_variables[check]))), np.ones((1,len(checks_and_variables[check]))))
#                     values[:,checks_and_variables[check]==n] = np.array([[i],[i]])
                    
#                     for 

                    
                    
#                     for thing in checks_and_variables[item]:
#                         if thing != item:
#                             for j in range(2):
#                         print(H_hat[item, thing])
#                     #print(H_hat[item,])
#                     #pass #H_hat[item,:]@
                
            
            
            
        
                
    return initials
                
    
    

SyntaxError: invalid syntax (<ipython-input-125-55dbdf559e31>, line 61)

In [124]:
print(y1.shape)
print(ldpc_decoder(H1, y1, 0.1, max_iter = 20))

(1000, 1)
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


KeyboardInterrupt: 