# Assignment 3

## Question 1
### part a)

In [131]:
import numpy as np

In [132]:
H = np.array([[1,1,1,1,0,0],[0,0,1,1,0,1], [1,0,0,1,1,0]])

In [133]:
def system_encoding(H):
    n_rows, n_columns = H.shape
    H_hat = np.zeros((H.shape))
    
    for i in range(n_columns):
        H_hat[:,i] = H[:, i]
     
    for j in range(n_rows):
        found = False
        dummy = np.zeros((H.shape))
        for i in range(n_columns):
            if (np.sum(H_hat[:,i]) == 1) & (H_hat[j,i] == 1) & (found==False):
                dummy[:,n_columns-n_rows+j] = H_hat[:,i].T
                dummy[:,i] = H_hat[:, n_columns-n_rows+j]
                found = True
                    
            elif np.sum(dummy[:,i]) == 0:
                dummy[:,i] = H_hat[:,i]
        
        H_hat = dummy
    
            
    G = np.zeros((n_columns, n_columns-n_rows))
    G[:n_columns - n_rows, :n_columns - n_rows] = np.eye(N=n_columns-n_rows)
    G[n_columns - n_rows:, :n_columns - n_rows] = H_hat[:, :n_columns-n_rows]
    return H_hat, G

In [8]:
A = np.array([[1,0,1,0,0,1], [0,1,1,0,0,1], [0,0,0,0,1,1]])

In [9]:
B = np.array([[1,1,0,1,0,0], [0,0,1,1,0,0], [1,0,0,1,1,0], [0,0,0,0,0,1]])

In [10]:
C = np.array([[1,1,0,0,1,0],[1,1,0,0,0,1],[1,0,0,1,0,0]])

In [66]:
print(H)
print('\n')
H_bar,G_bar = system_encoding(H)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 1 1 0 0]
 [0 0 1 1 0 1]
 [1 0 0 1 1 0]]


[[1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]


In [67]:
print(np.sum(H_bar@G_bar@np.array([0,0,0]).T)%2)

0.0


In [68]:
print(A)
print('\n')
H_bar,G_bar = system_encoding(A)
print(H_bar)
print('\n')
print(G_bar)

[[1 0 1 0 0 1]
 [0 1 1 0 0 1]
 [0 0 0 0 1 1]]


[[0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 0.]]


In [69]:
print(B)
print('\n')
H_bar,G_bar = system_encoding(B)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 1 0 0]
 [0 0 1 1 0 0]
 [1 0 0 1 1 0]
 [0 0 0 0 0 1]]


[[1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


[[1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]]


In [70]:
print(C)
print('\n')
H_bar,G_bar = system_encoding(C)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 0 1 0]
 [1 1 0 0 0 1]
 [1 0 0 1 0 0]]


[[1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]]


In [78]:
D = np.array([[1,1,0,1,0,0],[0,0,1,1,0,1], [0,0,0,1,1,0]])
print(D)
print('\n')
H_bar,G_bar = system_encoding(D)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 1 0 0]
 [0 0 1 1 0 1]
 [0 0 0 1 1 0]]


[[1. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 0. 0.]]


### part c)

In [134]:
with open('H1.txt', 'r') as f:
    H1 = [[int(num) for num in line.split(' ')] for line in f]
H1 = np.array(H1)

with open('y1.txt', 'r') as f:
    y1 = [[int(num) for num in line.split(' ')] for line in f]
y1 = np.array(y1)   
H1_hat, G1 = system_encoding(H1)

In [135]:
print(H1.shape)
#print(G1.shape)
#print(np.sum(H1_hat))
#print(np.sum(H1_hat,axis=0)%2)

(750, 1000)


In [328]:
bin_seq = []

def genbin(n, bs = ''):
    if n-1:
        bs0 = bs+'0'#.append(0)
        bs1 = bs+'1' #.append(1)
        genbin(n-1, bs0)
        genbin(n-1, bs1)
    else:
        bin_seq.append([int(i) for i in bs])

genbin(5)
print(bin_seq)

[[0, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 0, 1, 1], [0, 1, 0, 0], [0, 1, 0, 1], [0, 1, 1, 0], [0, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 1], [1, 0, 1, 0], [1, 0, 1, 1], [1, 1, 0, 0], [1, 1, 0, 1], [1, 1, 1, 0], [1, 1, 1, 1]]


In [359]:
def perms(n):
    if not n:
        return

    for i in range(2**n):
        s = bin(i)[2:]
        s = "0" * (n-len(s)) + s
        yield s

#print(list(perms(5)))

In [360]:
def genBinary(n, i, pos_i):
    #generates binary sequences of length n for an i in pos_i position
    bin_seq = []
    for item in list(perms(n)):
        bin_seq.append([int(i) for i in item])
        
    sequence = np.array(bin_seq)
    
    sequence[:, pos_i] = i*np.ones((1,2**(n)))
    
    
    return sequence

In [480]:
def ldpc_decoder(H_hat, y, p, max_iter = 20):
    # This function should be used to do loopy belief propogation on our recieved signal y and return a vector
    # which reperesents the decoded output message.
    # This function should work on the assumption we using the Binary symetric channel
    # It should also output a zero if the a solution was reached and algorithm converged and -1 if it is not.
    
    # Going to need to set up priors and messages which are going to be sent around the system 
    
    n_rows, n_cols = H_hat.shape
    
    # n_rows is the number of partity checks we have and therefore factors in our graph 
    # So we need to go over the iterations and do a pass throuhg the whole system
    # n_cols is the number of features we have 
    
    # 1) Initialise (outside for loop) - p(yn|xn)
    # 2) Factor to variable messages
    # 3) Variable to factor messages
    # 4) Calculate marginals - go back through the steps after this
    
    initials = np.zeros((2, n_cols))
    
    #Here compute the initail probs P(yn|xn) for each value of xn and given yn values (these are first var to factor messages)
    for n in range(n_cols):
        for i in range(2):
            initials[i,n] = p**((i-y[n,0])%2)*(1-p)**((i-y[n,0]+1)%2)
    
    #Define a dictionary has each variable and the checks associatied with it
    variables_and_checks = {}
    checks_and_variables = {}
    #cylce over variables
    for n in range(n_cols):
        #cycle of checks
        for m in range(n_rows):
            if H_hat[m,n] == 1 and (n not in variables_and_checks):
                variables_and_checks[n] = [m]
            elif H_hat[m,n] == 1:
                variables_and_checks[n].append(m)
                
            if H_hat[m,n] == 1 and (m not in checks_and_variables):
                checks_and_variables[m] = [n]
            elif H_hat[m,n] == 1:
                checks_and_variables[m].append(n)
                
    #print(variables_and_checks)
    #print(checks_and_variables)
    
    #Marginals - initialise the marginals that will beproduced at each each iteration
    marginals = {}
    
    #Intitalise the factor to variable messages
    messages_fv = {}
    
    #Initialise the variable to factor messages
    messages_vf = {}
    
    # Now we go through each iteration and doing all message passing
    for iTer in range(max_iter):
        
        # We compute factor to variable messages based off the parity check matrix
        for n in range(n_cols):
            mess = np.zeros((2, len(variables_and_checks[n])))
            # Now lets loop through the checks we need to do
            for check in variables_and_checks[n]:
                # loop through the possible values of our variable and generate tbe messages assoicated with it.
                for i in range(2):
                    # The number of varlues in this parity check are as follows
                    num_parity_bits = len(checks_and_variables[check])
                    
                    tries = genBinary(num_parity_bits, i, checks_and_variables[check].index(n))
                    
                    for row in range(tries.shape[0]):
                        if np.sum(tries[row,:])%2 == 0:
                            product = 1
                            for num in range(len(tries[row,:])): 
                                if checks_and_variables[check][num]!= n:
                                    # Times by the associated messages.
                                    
                                    product *= initials[tries[row,num],checks_and_variables[check][num]]
                                    
                            mess[i, variables_and_checks[n].index(check)] += product
                                    
            messages_fv[n] = mess
            
        #Now we want to compute all messages from variables to factors
        
        #Cycle over all factors
        for m in range(n_rows):
            #intiialise the matrix of all variables associated with the factor
            mess = np.zeros((2, len(checks_and_variables[m])))
            
            for var in checks_and_variables[m]:
                 for i in range(2):
                        # initialise with P(yn|xn)
                        mess[i,checks_and_variables[m].index(var)] = initials[i, var]
                        # Now multiple by the messages from factors to that variable
                        
                        for num in range(len(variables_and_checks[var])):
                            if variables_and_checks[var][num] != m:
                                mess[i,checks_and_variables[m].index(var)] *= messages_fv[var][i,num]
                                
            messages_vf[m] = mess
                                
                                
    # Next need to compute marginals                    
                        
            
    print(messages_fv)
    print(messages_vf)
              
    return initials
                

In [443]:
print(ldpc_decoder(H1, y1, p, max_iter = 1))

In [151]:
def bsc_noiser(x, p):
    # This function takes in a message x and puts it through a noisy channel outputting the noisey version
    y = np.zeros((x.shape))
    
    for i in range(x.shape[0]):
        ran_num = np.random.rand()
        if ran_num <= p:
            y[i,0] = (x[i,0]+1)%2
        else:
            y[i,0] = x[i,0]
            
    return y 

In [479]:
H = np.array([[1,1,1,1,0,0],[0,0,1,1,0,1], [1,0,0,1,1,0]])

p = 0.1

x = np.array([[0],[1],[0]])

H_hat, G = system_encoding(H)

message =G@x

signal = bsc_noiser(message, p)

print(message.T)
print(signal.T)

decoded_message = ldpc_decoder(H, signal, p)
print(decoded_message)


[[0. 1. 0. 1. 1. 1.]]
[[0. 1. 0. 1. 1. 1.]]
{0: array([[1.512, 1.64 ],
       [0.488, 0.36 ]]), 1: array([[0.488],
       [1.512]]), 2: array([[1.512, 1.64 ],
       [0.488, 0.36 ]]), 3: array([[0.488, 0.36 , 0.36 ],
       [1.512, 1.64 , 1.64 ]]), 4: array([[0.36],
       [1.64]]), 5: array([[0.36],
       [1.64]])}
{0: array([[1.476  , 0.1    , 1.476  , 0.01296],
       [0.036  , 0.9    , 0.036  , 2.42064]]), 1: array([[1.3608  , 0.017568, 0.1     ],
       [0.0488  , 2.231712, 0.9     ]]), 2: array([[1.3608  , 0.017568, 0.1     ],
       [0.0488  , 2.231712, 0.9     ]])}
[[0.9 0.1 0.9 0.1 0.1 0.1]
 [0.1 0.9 0.1 0.9 0.9 0.9]]
