# Assignment 3

## Question 1
### part a)

In [5]:
import numpy as np

In [6]:
H = np.array([[1,1,1,1,0,0],[0,0,1,1,0,1], [1,0,0,1,1,0]])

In [65]:
def system_encoding(H):
    n_rows, n_columns = H.shape
    H_hat = np.zeros((H.shape))
    
    for i in range(n_columns):
        H_hat[:,i] = H[:, i]
     
    
    for j in range(n_rows):
        found = False
        dummy = np.zeros((H.shape))
        for i in range(n_columns):
            if (np.sum(H_hat[:,i]) == 1) & (H_hat[j,i] == 1) & (found==False):
                dummy[:,n_columns-n_rows+j] = H_hat[:,i].T
                dummy[:,i] = H_hat[:, n_columns-n_rows+j]
                found = True
                    
            elif np.sum(dummy[:,i]) == 0:
                dummy[:,i] = H_hat[:,i]
        
        H_hat = dummy
    
            
    G = np.zeros((n_columns, n_columns-n_rows))
    G[:n_columns - n_rows, :n_columns - n_rows] = np.eye(N=n_columns-n_rows)
    G[n_columns - n_rows:, :n_columns - n_rows] = H_hat[:, :n_columns-n_rows]
    return H_hat, G

In [8]:
A = np.array([[1,0,1,0,0,1], [0,1,1,0,0,1], [0,0,0,0,1,1]])

In [9]:
B = np.array([[1,1,0,1,0,0], [0,0,1,1,0,0], [1,0,0,1,1,0], [0,0,0,0,0,1]])

In [10]:
C = np.array([[1,1,0,0,1,0],[1,1,0,0,0,1],[1,0,0,1,0,0]])

In [66]:
print(H)
print('\n')
H_bar,G_bar = system_encoding(H)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 1 1 0 0]
 [0 0 1 1 0 1]
 [1 0 0 1 1 0]]


[[1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]


In [67]:
print(np.sum(H_bar@G_bar@np.array([0,0,0]).T)%2)

0.0


In [68]:
print(A)
print('\n')
H_bar,G_bar = system_encoding(A)
print(H_bar)
print('\n')
print(G_bar)

[[1 0 1 0 0 1]
 [0 1 1 0 0 1]
 [0 0 0 0 1 1]]


[[0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 0.]]


In [69]:
print(B)
print('\n')
H_bar,G_bar = system_encoding(B)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 1 0 0]
 [0 0 1 1 0 0]
 [1 0 0 1 1 0]
 [0 0 0 0 0 1]]


[[1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


[[1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]]


In [70]:
print(C)
print('\n')
H_bar,G_bar = system_encoding(C)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 0 1 0]
 [1 1 0 0 0 1]
 [1 0 0 1 0 0]]


[[1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]]


In [78]:
D = np.array([[1,1,0,1,0,0],[0,0,1,1,0,1], [0,0,0,1,1,0]])
print(D)
print('\n')
H_bar,G_bar = system_encoding(D)
print(H_bar)
print('\n')
print(G_bar)

[[1 1 0 1 0 0]
 [0 0 1 1 0 1]
 [0 0 0 1 1 0]]


[[1. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 0. 0.]]


### part c)

In [72]:
with open('H1.txt', 'r') as f:
    H1 = [[int(num) for num in line.split(' ')] for line in f]
H1 = np.array(H1)

with open('y1.txt', 'r') as f:
    y1 = [[int(num) for num in line.split(' ')] for line in f]
y1 = np.array(y1)   
H1_hat, G1 = system_encoding(H1)

In [88]:
print(H1.shape)
print(G1.shape)
print(np.sum(H1_hat))
#print(np.sum(H1_hat,axis=0)%2)

(750, 1000)
(1000, 250)
3000.0


In [ ]:
def ldpc_decoder(H_hat, y, p, max_iter = 20):
    # This function should be used to do loopy belief propogation on our recieved signal y and return a vector
    # which reperesents the decoded output message.
    # This function should work on the assumption we using the Binary symetric channel
    # It should also output a zero if the a solution was reached and algorithm converged and -1 if it is not.
    
    # Going to need to set up priors and messages which are going to be sent around the system 